### PR TITLE
reduce some codacy issues

### PR DESCRIPTION
**Pull request by darkwizz**
updates to #41

### CODE REVIEW

**Comment by aviaryan** [comment]
Hi @darkwizz . There are some merge conflicts. Please fix them. 
Also I have removed the function complexity issue from codacy so they don't show in reports. It would be better if you send a PR again. Thanks

**Comment by darkwizz** [comment]
hello, can you send, please,

**Comment by darkwizz** [comment]
oh, sorry. Can you send

**Comment by darkwizz** [comment]
startScreen.java with highlighted conflicts?

**Comment by darkwizz** [comment]
and I thought that the person who merges need to decide what to remove and what to leave in merging commit

**Comment by aviaryan** [comment]
> and I thought that the person who merges need to decide what to remove and what to leave in merging commit

As you already have figured, it's not like that. I will have to merge every change that you make. It will be best if you create a new PR because there is a merge conflict here and to fix it, you will have to rebase your fork. (assuming you are new to git, this can be tricky)

**Pull request closed without merging**
