### PR TITLE
modified the start screen

### PR DESCRIPTION
**Pull request by Akatsuki06**
Changed the game start screen look, made it more like a game than app;

### CODE REVIEW

**Comment by aviaryan** [comment]
Hey @Akatsuki06 . This looks awesome. Can you please remove screenshot.png , we don't need an unneccessary binary file in the repo. Instead you can upload the screenshot on http://postimg.org/ and link it here.

**Review by aviaryan — CHANGES_REQUESTED** [review]
Remove screenshot

**Comment by Akatsuki06** [comment]
okay sir i will do that

**Comment by aviaryan** [comment]
See https://github.com/aviaryan/Hinix/issues/13#issuecomment-253628642

**Pull request closed without merging**
