### PR TITLE
Reduced space from margins #1

### PR DESCRIPTION
**Pull request by wadleo**
Fix for bug #1

### CODE REVIEW

**Comment by aviaryan** [comment]
Hey @wadleo , can you show us a screenshot on how the screen looks after reducing the margins. Thanks

**Comment by wadleo** [comment]
Ok give me a minute

**Comment by wadleo** [comment]
Easy, Moderate and Hard Screenshots respectively
hinix_small
hinix_medium
hinix_large

**Review by aviaryan — APPROVED** [review]
LGTM

**Review by RajuKoushik — APPROVED** [review]
Great work @wadleo .  Cheers.

**Pull request merged**
