### PR TITLE
Minimum SDK Version Reduced to15

### PR DESCRIPTION
**Pull request by karanjuneja1106**

### CODE REVIEW

**Comment by karanjuneja1106** [comment]
@aviaryan Finally the issue is resolved

**Comment by aviaryan** [comment]
Great work @karanjuneja1106 . Will merge it after testing

**Comment by aviaryan** [comment]
@karanjuneja1106 On my CM 13 (Marshmallow), the grid is being scaled down horizontally. I tried the easy mode. Can you please check ?

**Comment by karanjuneja1106** [comment]
@aviaryan check it now

**Comment by aviaryan** [comment]
@karanjuneja1106 Hey, the results are still not the same as before. [see screenshots at google play](https://play.google.com/store/apps/details?id=in.aviaryan.hinix)
The tiles are square but they don't cover entire screen width and thus are not centered. 
I guess this is because of `minWidthMargin` of 80. I am not sure why this was added in the first place. Can you please explain?

**Comment by karanjuneja1106** [comment]
i tested the game on screen sizes less than or equal to 480 X 800 hdpi. Game board size was larger than the screen size. So i added it as a check if the game board's size is having enough margin.

**Comment by karanjuneja1106** [comment]
@aviaryan Check the changes
edit:Removed minWidthMargin

**Review by aviaryan — APPROVED** [review]

**Comment by aviaryan** [comment]
@karanjuneja1106 Sorry for the delay. Was not well in the last few days.

**Pull request merged**
