### PR TITLE
Issue Fixed:Reduce Minimum SDK Version

### PR DESCRIPTION
**Pull request by karanjuneja1106**
New MInimum SDK Version:15 (Android 4.04)

### CODE REVIEW

**Comment by aviaryan** [comment]
@karanjuneja1106 please don't commit files in .idea . See CONTRIBUTING.md
Edit - Thanks for the PR, btw.

**Comment by karanjuneja1106** [comment]
So if i do not commit the .idea directory files ,will this issue of failed PR be fixed?
PS:i am a noob to Open Source

**Comment by aviaryan** [comment]
@karanjuneja1106 no. that wouldn't happen. 
PS - it would be better if you re-fork this repo and send a different PR. There are merge conflicts.

**Comment by karanjuneja1106** [comment]
@aviaryan just one more question
shall i include app\app.iml and app\build.gradle

**Pull request closed without merging**
